// Generated from PokéAPI Gen I species, English names and base stats.
// Existing hand-tuned Pokémon in data.js take precedence.
const p = (name, zone, hp, power, price, color, shape, ability, abilityText) => ({ name, zone, hp, power, price, color, shape, ability, abilityText });
export const EXTRA_POKEMON = {
  "weedle": p("Weedle", "green", 4, 2, 2, "#a78b6d", "mouse", "power", "โจมตีครั้งแรก +1"),
  "kakuna": p("Kakuna", "blue", 7, 2, 7, "#dfbf63", "fish", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "beedrill": p("Beedrill", "purple", 10, 5, 13, "#dfbf63", "dragon", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "spearow": p("Spearow", "green", 4, 3, 3, "#a78b6d", "bird", "power", "โจมตีครั้งแรก +1"),
  "fearow": p("Fearow", "blue", 8, 4, 7, "#a78b6d", "bird", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "ekans": p("Ekans", "green", 4, 3, 3, "#a48ec0", "fish", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "arbok": p("Arbok", "blue", 8, 4, 7, "#a48ec0", "fish", "heal", "หลังชนะฟื้น 1 HP"),
  "sandshrew": p("Sandshrew", "green", 5, 3, 4, "#dfbf63", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "sandslash": p("Sandslash", "blue", 9, 4, 8, "#dfbf63", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "nidoran-m": p("Nidoran♂", "green", 5, 3, 3, "#a48ec0", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "nidorino": p("Nidorino", "blue", 8, 3, 7, "#a48ec0", "bear", "power", "โจมตีครั้งแรก +1"),
  "nidoking": p("Nidoking", "purple", 11, 6, 15, "#a48ec0", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "clefairy": p("Clefairy", "green", 6, 2, 3, "#dea2bc", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "clefable": p("Clefable", "blue", 10, 3, 8, "#dea2bc", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "vulpix": p("Vulpix", "green", 4, 2, 2, "#a78b6d", "bear", "power", "โจมตีครั้งแรก +1"),
  "ninetales": p("Ninetales", "blue", 9, 3, 7, "#dfbf63", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "jigglypuff": p("Jigglypuff", "green", 8, 2, 5, "#dea2bc", "ghost", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "wigglytuff": p("Wigglytuff", "blue", 11, 3, 10, "#dea2bc", "ghost", "heal", "หลังชนะฟื้น 1 HP"),
  "zubat": p("Zubat", "green", 4, 2, 2, "#a48ec0", "bird", "power", "โจมตีครั้งแรก +1"),
  "golbat": p("Golbat", "blue", 9, 3, 7, "#a48ec0", "bird", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "paras": p("Paras", "green", 4, 3, 3, "#d88179", "mouse", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "parasect": p("Parasect", "blue", 8, 4, 7, "#d88179", "mouse", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "venonat": p("Venonat", "green", 5, 3, 3, "#a48ec0", "ghost", "heal", "หลังชนะฟื้น 1 HP"),
  "venomoth": p("Venomoth", "blue", 8, 3, 7, "#a48ec0", "dragon", "power", "โจมตีครั้งแรก +1"),
  "diglett": p("Diglett", "green", 4, 3, 2, "#a78b6d", "blob", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "dugtrio": p("Dugtrio", "blue", 7, 4, 7, "#a78b6d", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "meowth": p("Meowth", "green", 4, 2, 2, "#dfbf63", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "persian": p("Persian", "blue", 8, 3, 7, "#dfbf63", "bear", "power", "โจมตีครั้งแรก +1"),
  "psyduck": p("Psyduck", "green", 5, 2, 3, "#dfbf63", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "golduck": p("Golduck", "blue", 9, 3, 8, "#6eadd2", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "mankey": p("Mankey", "green", 4, 3, 3, "#a78b6d", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "primeape": p("Primeape", "blue", 8, 4, 8, "#a78b6d", "bear", "power", "โจมตีครั้งแรก +1"),
  "growlithe": p("Growlithe", "green", 5, 3, 4, "#a78b6d", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "arcanine": p("Arcanine", "blue", 10, 4, 10, "#a78b6d", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "poliwag": p("Poliwag", "green", 4, 2, 3, "#6eadd2", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "poliwhirl": p("Poliwhirl", "blue", 8, 3, 7, "#6eadd2", "ghost", "power", "โจมตีครั้งแรก +1"),
  "poliwrath": p("Poliwrath", "purple", 12, 5, 15, "#6eadd2", "ghost", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "abra": p("Abra", "green", 4, 2, 2, "#a78b6d", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "kadabra": p("Kadabra", "blue", 7, 2, 7, "#a78b6d", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "alakazam": p("Alakazam", "purple", 10, 4, 13, "#a78b6d", "ghost", "power", "โจมตีครั้งแรก +1"),
  "machop": p("Machop", "green", 6, 3, 4, "#9aa5a7", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "machoke": p("Machoke", "blue", 9, 4, 9, "#9aa5a7", "ghost", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "machamp": p("Machamp", "purple", 12, 6, 18, "#9aa5a7", "ghost", "heal", "หลังชนะฟื้น 1 HP"),
  "bellsprout": p("Bellsprout", "green", 5, 3, 4, "#75ae78", "ghost", "power", "โจมตีครั้งแรก +1"),
  "weepinbell": p("Weepinbell", "blue", 8, 4, 7, "#75ae78", "blob", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "victreebel": p("Victreebel", "purple", 11, 6, 15, "#75ae78", "blob", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "tentacool": p("Tentacool", "green", 4, 2, 2, "#6eadd2", "bug", "heal", "หลังชนะฟื้น 1 HP"),
  "tentacruel": p("Tentacruel", "blue", 9, 3, 7, "#6eadd2", "bug", "power", "โจมตีครั้งแรก +1"),
  "geodude": p("Geodude", "green", 4, 3, 3, "#a78b6d", "lizard", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "graveler": p("Graveler", "blue", 7, 4, 7, "#a78b6d", "ghost", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "golem": p("Golem", "purple", 11, 6, 17, "#a78b6d", "ghost", "heal", "หลังชนะฟื้น 1 HP"),
  "ponyta": p("Ponyta", "green", 5, 3, 4, "#dfbf63", "bear", "power", "โจมตีครั้งแรก +1"),
  "rapidash": p("Rapidash", "blue", 8, 4, 8, "#dfbf63", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "slowpoke": p("Slowpoke", "green", 7, 3, 4, "#dea2bc", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "slowbro": p("Slowbro", "blue", 10, 3, 8, "#dea2bc", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "magnemite": p("Magnemite", "green", 4, 2, 2, "#9aa5a7", "lizard", "power", "โจมตีครั้งแรก +1"),
  "magneton": p("Magneton", "blue", 7, 3, 7, "#9aa5a7", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "farfetchd": p("Farfetch’d", "red", 10, 5, 17, "#a78b6d", "bird", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "doduo": p("Doduo", "green", 4, 3, 3, "#a78b6d", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "dodrio": p("Dodrio", "blue", 8, 4, 8, "#a78b6d", "bear", "power", "โจมตีครั้งแรก +1"),
  "seel": p("Seel", "green", 6, 2, 3, "#d7d8d0", "fish", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "dewgong": p("Dewgong", "blue", 10, 3, 8, "#d7d8d0", "fish", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "grimer": p("Grimer", "green", 6, 3, 5, "#a48ec0", "lizard", "heal", "หลังชนะฟื้น 1 HP"),
  "muk": p("Muk", "blue", 11, 4, 10, "#a48ec0", "lizard", "power", "โจมตีครั้งแรก +1"),
  "shellder": p("Shellder", "green", 4, 3, 3, "#a48ec0", "blob", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "cloyster": p("Cloyster", "blue", 7, 4, 7, "#a48ec0", "blob", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "gastly": p("Gastly", "green", 4, 2, 2, "#a48ec0", "blob", "heal", "หลังชนะฟื้น 1 HP"),
  "haunter": p("Haunter", "blue", 7, 2, 7, "#a48ec0", "lizard", "power", "โจมตีครั้งแรก +1"),
  "gengar": p("Gengar", "purple", 10, 4, 13, "#a48ec0", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "onix": p("Onix", "red", 10, 4, 17, "#9aa5a7", "fish", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "drowzee": p("Drowzee", "green", 5, 2, 3, "#dfbf63", "ghost", "heal", "หลังชนะฟื้น 1 HP"),
  "hypno": p("Hypno", "blue", 9, 3, 8, "#dfbf63", "ghost", "power", "โจมตีครั้งแรก +1"),
  "krabby": p("Krabby", "green", 4, 3, 4, "#d88179", "mouse", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "kingler": p("Kingler", "blue", 7, 5, 9, "#d88179", "mouse", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "voltorb": p("Voltorb", "green", 4, 2, 2, "#d88179", "blob", "heal", "หลังชนะฟื้น 1 HP"),
  "electrode": p("Electrode", "blue", 8, 2, 7, "#d88179", "blob", "power", "โจมตีครั้งแรก +1"),
  "exeggcute": p("Exeggcute", "green", 5, 2, 3, "#dea2bc", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "exeggutor": p("Exeggutor", "blue", 10, 4, 9, "#dfbf63", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "cubone": p("Cubone", "green", 5, 2, 3, "#a78b6d", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "marowak": p("Marowak", "blue", 8, 3, 7, "#a78b6d", "bear", "power", "โจมตีครั้งแรก +1"),
  "hitmonlee": p("Hitmonlee", "red", 10, 6, 17, "#a78b6d", "ghost", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "hitmonchan": p("Hitmonchan", "red", 10, 6, 17, "#a78b6d", "ghost", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "lickitung": p("Lickitung", "red", 13, 4, 17, "#dea2bc", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "koffing": p("Koffing", "green", 4, 3, 3, "#a48ec0", "blob", "power", "โจมตีครั้งแรก +1"),
  "weezing": p("Weezing", "blue", 8, 4, 7, "#a48ec0", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "rhyhorn": p("Rhyhorn", "green", 6, 3, 5, "#9aa5a7", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "rhydon": p("Rhydon", "blue", 11, 5, 11, "#9aa5a7", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "tangela": p("Tangela", "red", 11, 4, 17, "#6eadd2", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "horsea": p("Horsea", "green", 4, 2, 2, "#6eadd2", "blob", "heal", "หลังชนะฟื้น 1 HP"),
  "seadra": p("Seadra", "blue", 7, 3, 7, "#6eadd2", "blob", "power", "โจมตีครั้งแรก +1"),
  "goldeen": p("Goldeen", "green", 4, 3, 3, "#d88179", "fish", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "seaking": p("Seaking", "blue", 9, 4, 8, "#d88179", "fish", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "staryu": p("Staryu", "green", 4, 2, 2, "#a78b6d", "blob", "heal", "หลังชนะฟื้น 1 HP"),
  "starmie": p("Starmie", "blue", 8, 3, 7, "#a48ec0", "blob", "power", "โจมตีครั้งแรก +1"),
  "mr-mime": p("Mr. Mime", "red", 10, 4, 17, "#dea2bc", "ghost", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "jynx": p("Jynx", "red", 11, 4, 17, "#d88179", "ghost", "heal", "หลังชนะฟื้น 1 HP"),
  "electabuzz": p("Electabuzz", "red", 11, 5, 17, "#dfbf63", "bear", "power", "โจมตีครั้งแรก +1"),
  "magmar": p("Magmar", "red", 11, 6, 17, "#d88179", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "pinsir": p("Pinsir", "red", 11, 7, 19, "#a78b6d", "ghost", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "eevee": p("Eevee", "green", 5, 3, 3, "#a78b6d", "bear", "power", "โจมตีครั้งแรก +1"),
  "vaporeon": p("Vaporeon", "blue", 11, 3, 9, "#6eadd2", "bear", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "jolteon": p("Jolteon", "blue", 8, 3, 7, "#dfbf63", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "flareon": p("Flareon", "blue", 8, 5, 9, "#d88179", "bear", "heal", "หลังชนะฟื้น 1 HP"),
  "porygon": p("Porygon", "red", 11, 4, 17, "#dea2bc", "bear", "power", "โจมตีครั้งแรก +1"),
  "omanyte": p("Omanyte", "red", 10, 4, 17, "#6eadd2", "bug", "dodge", "ลดความเสียหายครั้งแรก 1"),
  "omastar": p("Omastar", "red", 12, 4, 17, "#6eadd2", "bug", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
  "kabuto": p("Kabuto", "red", 10, 5, 17, "#a78b6d", "mouse", "heal", "หลังชนะฟื้น 1 HP"),
  "kabutops": p("Kabutops", "red", 11, 6, 18, "#a78b6d", "bear", "power", "โจมตีครั้งแรก +1"),
  "mew": p("Mew", "legendary", 15, 6, 25, "#dea2bc", "bear", "sale", "ขายได้เพิ่ม 1 เหรียญ"),
};
export const EXTRA_EVOLUTIONS = {
  "weedle": "kakuna",
  "kakuna": "beedrill",
  "spearow": "fearow",
  "ekans": "arbok",
  "sandshrew": "sandslash",
  "nidoran-m": "nidorino",
  "nidorino": "nidoking",
  "clefairy": "clefable",
  "vulpix": "ninetales",
  "jigglypuff": "wigglytuff",
  "zubat": "golbat",
  "paras": "parasect",
  "venonat": "venomoth",
  "diglett": "dugtrio",
  "meowth": "persian",
  "psyduck": "golduck",
  "mankey": "primeape",
  "growlithe": "arcanine",
  "poliwag": "poliwhirl",
  "poliwhirl": "poliwrath",
  "abra": "kadabra",
  "kadabra": "alakazam",
  "machop": "machoke",
  "machoke": "machamp",
  "bellsprout": "weepinbell",
  "weepinbell": "victreebel",
  "tentacool": "tentacruel",
  "geodude": "graveler",
  "graveler": "golem",
  "ponyta": "rapidash",
  "slowpoke": "slowbro",
  "magnemite": "magneton",
  "doduo": "dodrio",
  "seel": "dewgong",
  "grimer": "muk",
  "shellder": "cloyster",
  "gastly": "haunter",
  "haunter": "gengar",
  "drowzee": "hypno",
  "krabby": "kingler",
  "voltorb": "electrode",
  "exeggcute": "exeggutor",
  "cubone": "marowak",
  "koffing": "weezing",
  "rhyhorn": "rhydon",
  "horsea": "seadra",
  "goldeen": "seaking",
  "staryu": "starmie",
  "eevee": "vaporeon",
  "omanyte": "omastar",
  "kabuto": "kabutops",
};
export const EXTRA_POKEDEX = {
  "weedle": 13,
  "kakuna": 14,
  "beedrill": 15,
  "spearow": 21,
  "fearow": 22,
  "ekans": 23,
  "arbok": 24,
  "sandshrew": 27,
  "sandslash": 28,
  "nidoran-m": 32,
  "nidorino": 33,
  "nidoking": 34,
  "clefairy": 35,
  "clefable": 36,
  "vulpix": 37,
  "ninetales": 38,
  "jigglypuff": 39,
  "wigglytuff": 40,
  "zubat": 41,
  "golbat": 42,
  "paras": 46,
  "parasect": 47,
  "venonat": 48,
  "venomoth": 49,
  "diglett": 50,
  "dugtrio": 51,
  "meowth": 52,
  "persian": 53,
  "psyduck": 54,
  "golduck": 55,
  "mankey": 56,
  "primeape": 57,
  "growlithe": 58,
  "arcanine": 59,
  "poliwag": 60,
  "poliwhirl": 61,
  "poliwrath": 62,
  "abra": 63,
  "kadabra": 64,
  "alakazam": 65,
  "machop": 66,
  "machoke": 67,
  "machamp": 68,
  "bellsprout": 69,
  "weepinbell": 70,
  "victreebel": 71,
  "tentacool": 72,
  "tentacruel": 73,
  "geodude": 74,
  "graveler": 75,
  "golem": 76,
  "ponyta": 77,
  "rapidash": 78,
  "slowpoke": 79,
  "slowbro": 80,
  "magnemite": 81,
  "magneton": 82,
  "farfetchd": 83,
  "doduo": 84,
  "dodrio": 85,
  "seel": 86,
  "dewgong": 87,
  "grimer": 88,
  "muk": 89,
  "shellder": 90,
  "cloyster": 91,
  "gastly": 92,
  "haunter": 93,
  "gengar": 94,
  "onix": 95,
  "drowzee": 96,
  "hypno": 97,
  "krabby": 98,
  "kingler": 99,
  "voltorb": 100,
  "electrode": 101,
  "exeggcute": 102,
  "exeggutor": 103,
  "cubone": 104,
  "marowak": 105,
  "hitmonlee": 106,
  "hitmonchan": 107,
  "lickitung": 108,
  "koffing": 109,
  "weezing": 110,
  "rhyhorn": 111,
  "rhydon": 112,
  "tangela": 114,
  "horsea": 116,
  "seadra": 117,
  "goldeen": 118,
  "seaking": 119,
  "staryu": 120,
  "starmie": 121,
  "mr-mime": 122,
  "jynx": 124,
  "electabuzz": 125,
  "magmar": 126,
  "pinsir": 127,
  "eevee": 133,
  "vaporeon": 134,
  "jolteon": 135,
  "flareon": 136,
  "porygon": 137,
  "omanyte": 138,
  "omastar": 139,
  "kabuto": 140,
  "kabutops": 141,
  "mew": 151,
};
